// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudS2Tc0ZEJtG6i300pk3W8QsVkjcFrR4',
    appId: '1:188315644914:web:821a2b31df1a02aa25316b',
    messagingSenderId: '188315644914',
    projectId: 'portfolio-a62eb',
    authDomain: 'portfolio-a62eb.firebaseapp.com',
    storageBucket: 'portfolio-a62eb.firebasestorage.app',
    measurementId: 'G-T7GDFNJJTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGRu-mWh5rPfSdswzMDVz2QdN6Q5MBbA8',
    appId: '1:188315644914:android:b1fbaa80452828d825316b',
    messagingSenderId: '188315644914',
    projectId: 'portfolio-a62eb',
    storageBucket: 'portfolio-a62eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXTqLsZSXUKwrc0Z964QRU_1Lfh-MDsA',
    appId: '1:188315644914:ios:76063d4a4d55556725316b',
    messagingSenderId: '188315644914',
    projectId: 'portfolio-a62eb',
    storageBucket: 'portfolio-a62eb.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXTqLsZSXUKwrc0Z964QRU_1Lfh-MDsA',
    appId: '1:188315644914:ios:76063d4a4d55556725316b',
    messagingSenderId: '188315644914',
    projectId: 'portfolio-a62eb',
    storageBucket: 'portfolio-a62eb.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudS2Tc0ZEJtG6i300pk3W8QsVkjcFrR4',
    appId: '1:188315644914:web:9d09a13245e1057425316b',
    messagingSenderId: '188315644914',
    projectId: 'portfolio-a62eb',
    authDomain: 'portfolio-a62eb.firebaseapp.com',
    storageBucket: 'portfolio-a62eb.firebasestorage.app',
    measurementId: 'G-7MGY6MQBCY',
  );
}
